### PR TITLE
Introduce SemanticDB-based rsc.symtab.Symtab

### PR DESCRIPTION
**Pull request by xeno-by**
This PR adds another implementation of a symbol table to Rsc.
This one is based solely on SemanticDB data structures and, as a result,
can interoperate with binary dependencies preprocessed by metacp.

In order to make sure that we're aware of performance implications,
I'm not replacing the old symbol table with the new one right away.
Instead, I'm planning to turn this into a set of small steps, with
every step carefully benchmarked.

This gradual process will require some additional ceremony during
the transition period while both symbol tables coexist. I think this
is well-justified given the benefits of iterative development that
the transition period will enable.

### CODE REVIEW

**Comment by rscbenchbox** [comment]
Accepted benchmarking [8294737](https://github.com/xeno-by/rsc/commit/8294737216225ff05779592766597f723305fc93). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [221a9de](https://github.com/xeno-by/rsc/commit/221a9de744e89693e8f4f55e00f7584a25e2e285). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [7d764b0](https://github.com/xeno-by/rsc/commit/7d764b0c74361c581e6970fb70f5f6dc974c92c2). This may take a while.

**Comment by rscbenchbox** [comment]
Finished benchmarking [7d764b0](https://github.com/xeno-by/rsc/commit/7d764b0c74361c581e6970fb70f5f6dc974c92c2).

| Benchmark          | Before | After |
|--------------------|--------|-------|
| RscNativeTypecheck | 64.756 ms     | 72.241 ms    |
| RscTypecheck       | 26.062 ms     | 26.279 ms    |

Full results are available at https://github.com/twitter/rsc/commit/edd097d6dacaa91e3c9b91f1986f01c62f81db24.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [ce9e8fd](https://github.com/xeno-by/rsc/commit/ce9e8fde70ef34325dc5a8a60ea44a0f10cd6382). This may take a while.

**Comment by xeno-by** [comment]
@rscbenchbox Changes ce9e8fd don't affect performance. I'll be merging.

**Pull request merged**
