### PR TITLE
Implement PackageScope.members

### PR DESCRIPTION
**Pull request by xeno-by**
In addition to providing an implementation for PackageScope.members,
this commit also changes PackageScope._storage to LinkedHashMap
to preserve insertion order.

This doesn't help much at the moment, because semanticdb.semanticidx
is pretty insane (https://github.com/scalameta/scalameta/issues/1457),
but I hope to address that soon.

### CODE REVIEW

**Comment by rscbenchbox** [comment]
Blocked benchmarking [88fe35e](https://github.com/xeno-by/rsc/commit/88fe35ea492e5b1a05ce69dc1287f29d4a65e838). First, I'm planning to benchmark [2b921d9](https://github.com/twitter/rsc/commit/2b921d90f601a424c4fbdaf680a563e6d2f20208), and then I'll get back to this commit.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [88fe35e](https://github.com/xeno-by/rsc/commit/88fe35ea492e5b1a05ce69dc1287f29d4a65e838). This may take a while.

**Comment by rscbenchbox** [comment]
Finished benchmarking [88fe35e](https://github.com/xeno-by/rsc/commit/88fe35ea492e5b1a05ce69dc1287f29d4a65e838).

| Benchmark          | Before | After |
|--------------------|--------|-------|
| RscNativeTypecheck | 73.989 ms     | 81.700 ms    |
| RscTypecheck       | 26.255 ms     | 26.856 ms    |

Full results are available at https://github.com/twitter/rsc/commit/a1a3306a7c04965e7b998feda3df0648412e17ef.

**Comment by xeno-by** [comment]
@rscbenchbox Thank you! It looks like the initial approach to this pull request introduces an unacceptable performance degradation. Let me give it another try.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [9625692](https://github.com/xeno-by/rsc/commit/9625692f7d1b7cf7182d5fb6bf13206259f96cc2). This may take a while.

**Comment by rscbenchbox** [comment]
Finished benchmarking [9625692](https://github.com/xeno-by/rsc/commit/9625692f7d1b7cf7182d5fb6bf13206259f96cc2).

| Benchmark          | Before | After |
|--------------------|--------|-------|
| RscNativeTypecheck | 73.989 ms     | 72.099 ms    |
| RscTypecheck       | 26.255 ms     | 26.287 ms    |

Full results are available at https://github.com/twitter/rsc/commit/36d2ed0b5500320dbaf4c8cbd5e243a8257dcaee.

**Comment by xeno-by** [comment]
@rscbenchbox 👍

**Pull request merged**
